# Generated by Django 4.2.16 on 2024-09-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=50)),
                ("movie_review", models.TextField(max_length=50)),
                ("movie_img", models.FileField(upload_to="movie/")),
            ],
        ),
    ]
